builder:
  track: dev

labels:
  app-group: estafette-various
  team: estafette-team
  language: docker

stages:
  bake:
    image: extensions/docker:dev
    action: build
    inline: |
      FROM scratch

      LABEL maintainer="estafette.io" \
            description="A runnable version of Docker's scratch container"
    no-cache: true
    container: scratch
    repositories:
    - estafette

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    container: scratch
    pushVersionTag: false
    repositories:
    - estafette
    tags:
    - latest